<a href="https://colab.research.google.com/github/akanchha-rani/movie-recommendation-ML-/blob/main/movie_recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the dependencies

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Data Collection and Pre-Processing

In [3]:
# loading the data from the csv file to apandas dataframes
movies_data = pd.read_csv('movies.csv')

In [4]:
# printing the first 5 rows of the dataframe
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [5]:
# number of rows and columns in the dataframes
movies_data.shape

(4803, 24)

In [32]:
# selecting the relevant features for recommendation
selected_features = ['genres','keywords','tagline','cast','director','overview']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director', 'overview']


In [33]:
# replacing the null values with null string
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [34]:
# combining all the 5 selected features
combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']+' '+movies_data['overview']

In [35]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [36]:
# convrting the text data to feature vectors
vectorizer = TfidfVectorizer()

In [37]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [38]:
print(feature_vectors)

  (0, 561)	0.05971816344971169
  (0, 703)	0.06846420517510078
  (0, 9754)	0.08513696797398294
  (0, 23977)	0.07941905576010944
  (0, 10023)	0.07960231361105431
  (0, 6601)	0.1498786462809525
  (0, 5279)	0.1549075340655008
  (0, 10796)	0.11095111375730655
  (0, 25413)	0.24369151759694266
  (0, 29469)	0.08637114089261566
  (0, 5592)	0.17322386697661618
  (0, 25232)	0.1336739112380023
  (0, 9065)	0.14505772980982928
  (0, 27118)	0.08328687324810813
  (0, 30121)	0.07272849549697494
  (0, 19410)	0.0318696249813729
  (0, 20039)	0.37747447361884223
  (0, 23619)	0.11047375838269538
  (0, 30145)	0.18243919685121024
  (0, 30543)	0.15064979633862852
  (0, 23578)	0.16802034155542864
  (0, 24802)	0.158925784923944
  (0, 29614)	0.15064979633862852
  (0, 25868)	0.11590870590502833
  (0, 15569)	0.171366691592621
  :	:
  (4802, 9588)	0.10415492266309316
  (4802, 21386)	0.08975511036766048
  (4802, 9166)	0.07829183421073847
  (4802, 24102)	0.08207980733784753
  (4802, 6136)	0.10774075928383217
  (4802, 

Cosine Similarity

In [39]:
# getting the similarity scores using cosine similarity
similarity = cosine_similarity(feature_vectors)

In [40]:
print(similarity)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [41]:
# getting the movie name from the user
movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : joker


In [42]:
# creating a list with all the movie names given in the dataset
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [43]:
# finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Stoker', 'Loser', 'Choke']


In [44]:
close_match = find_close_match[0]
print(close_match)

Stoker


In [45]:
# finding the index of the movie with title
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

2883


In [46]:
# getting a list of similar movies
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.036565159809182186), (1, 0.04014190262952873), (2, 0.010204306361304868), (3, 0.03976787308041722), (4, 0.028030172514017754), (5, 0.015244449172094209), (6, 0.05706598454362442), (7, 0.02011312261760148), (8, 0.004057264986980776), (9, 0.013679564896003749), (10, 0.017349707382532893), (11, 0.015219841498324727), (12, 0.006722234169119732), (13, 0.021916935167340536), (14, 0.03643750060681396), (15, 0.0227924490506605), (16, 0.005387023794000707), (17, 0.04833283798338364), (18, 0.030461109184491526), (19, 0.011109692621464756), (20, 0.063972258894255), (21, 0.01495033133697858), (22, 0.0089318631093263), (23, 0.08030459854856303), (24, 0.02517191596551792), (25, 0.05010150487636828), (26, 0.01736059613238293), (27, 0.047311153353664585), (28, 0.05753918601112455), (29, 0.07065246361050419), (30, 0.006350246975639696), (31, 0.0021431183733678512), (32, 0.10679194328877673), (33, 0.0074000387957253635), (34, 0.01970798167691793), (35, 0.012056888631095438), (36, 0.01031879535733

In [47]:
len(similarity_score)

4803

In [48]:
# sorting the movies based on their similarity score
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(2883, 1.0000000000000002), (2048, 0.1570744788481107), (3185, 0.15489836549212033), (3711, 0.14768550167228464), (1210, 0.13665662777163673), (4051, 0.13233302426529114), (2447, 0.13022698511091457), (2563, 0.12925620503161436), (2874, 0.12621014840341135), (1245, 0.1249374789594099), (1927, 0.12398477501830679), (1045, 0.12387783659881318), (1867, 0.1229830040630987), (812, 0.12279027043567217), (2554, 0.12154864485992889), (3280, 0.12082840365303468), (4044, 0.1203147262474278), (2239, 0.11922983342091087), (2180, 0.11791836632124598), (2137, 0.11784457049814816), (4719, 0.11742630360399081), (2173, 0.11582415279330183), (3922, 0.11466042106739643), (3558, 0.11435549799510997), (2026, 0.11324861678096028), (4692, 0.1129128474489732), (3254, 0.11213053921401052), (4795, 0.11173016726022184), (397, 0.1115166162961298), (4509, 0.11118861918256012), (3256, 0.1110039170518049), (3301, 0.10963444840184852), (3426, 0.10961706121347822), (4610, 0.10923046165475868), (1962, 0.10884308877577

In [49]:
# print the name of similar movies based on the index
print('Movies suggested for you : \n')
i=1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<10):
    print(i,'.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Stoker
2 . Darling Lili
3 . Gracie
4 . Sympathy for Lady Vengeance
5 . Gothika
6 . 8 Days
7 . Fur: An Imaginary Portrait of Diane Arbus
8 . Because of Winn-Dixie
9 . In the Cut


Movie Recommendation System

In [50]:
movie_name = input(' Enter your favourite movie name : ')
list_of_all_titles = movies_data['title'].tolist()
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
close_match = find_close_match[0]
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
similarity_score = list(enumerate(similarity[index_of_the_movie]))
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print('Movies suggested for you : \n')
i=1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<10):
    print(i,'.',title_from_index)
    i+=1

 Enter your favourite movie name : barbie
Movies suggested for you : 

1 . Submarine
2 . Next Friday
3 . Celeste & Jesse Forever
4 . Cinderella Man
5 . The Diary of a Teenage Girl
6 . You Will Meet a Tall Dark Stranger
7 . Layer Cake
8 . The Art of Getting By
9 . Carnage
